### ISSUE TITLE
Pbo files with captial letters crash linux servers

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#1]
**Arma 3 Version:** `1.84` stable
**CBA Version:** `3.x.x` stable
**ACE3 Version:** `3.x.x` stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Having .pbo files with capital letters crash linux servers. I have to rename them every time. Please replace the name of the .pbo with all lower case letters.

**Steps to reproduce:**
- Load a .pbo with capital letters.

**Where did the issue occur?**
- Dedicated Linux Server

**Comment by Katalam** [comment]
Closed - fixed
