### ISSUE TITLE
Feature request: Breathing

### ISSUE THREAD

**Issue by A-10** [Katalam/kat_aceAdvMedical#11]
### Breathing

- Pneumothorax/hemothorax (after Thorax hit) including decompressing needle and auscultation
- Oxygen Mask
- Ventilator

**Comment by Katalam** [comment]
The first idea of the pneumothorax is there. Check out eb925d6

The problem in adding things like ausculation is that i don't like it when you have no visual feedback. It would be horrible difficult to be able to hear the ausculation with a visual feedback like a arm going to the thorax.

A decompressing needle is not really needed. Of course in real-life you got tons of stuff to carry with you, but why not taking the ace surgical kit. If not it is just a new "useless" item to carry with you.

**Comment by jonvelz** [comment]
Just gonna toss my two cents in, the surgical kit is for clamping wounds, a pneumothorax requires a chest tube or decompression needle to actually treat it. 

I would say that you should also add things like tension pneumothorax, occlusive dressings aswell as respiratory failure that isn't the result of death, as to give the Bag Valve Mask a purpose.

**Comment by Katalam** [comment]
I will think about what @jonvelz said. But in my opinion it is a bit to much. A quote from the steam workshop: "I think we should just stop here. There's no reason to torture poor milsim playerbase medics and have people spend more time dead then alive" and he is right. 'Cause you shouldn't need a medical education for playing medic in a milsim game. I mean in things like a pneumothorax i can to it from knowledge, but not everyone. In case of a internal injury, i can't even script it without google the have of the facts.

(pneumothorax is on the list)

At the moment. Closed.
