### ISSUE TITLE
Feature request: Circulation

### ISSUE THREAD

**Issue by A-10** [Katalam/kat_aceAdvMedical#12]
### Circulation

- better Bloodpressure simulation (lower bloodpressure=less stamina), same for heartrate
- i.v. Canula
- Monitorbox with live tracking (RR, HF, spO2) on screen

**Comment by Katalam** [comment]
The monitorbox is already in the medical menu when you attach a AED X Series. Check out https://github.com/Katalam/kat_aceAdvMedical/blob/e553ba4f581a4898eb00595fba9e74bdc2e24fc0/addons/kat_aceCirculation/functions/fn_treatmentAdvanced_X.sqf#L35-L45

**Comment by Katalam** [comment]
The stamina is on the To-Do list. But it is not that easy. A lot of testing is required. But maybe one time it will be in it. The display is not needed in my opinion 'cause it is already in the medical menu.

At the moment. Closed.
