### ISSUE TITLE
Overstretch is not a requirement for intubation

### ISSUE THREAD

**Issue by corp-0** [Katalam/kat_aceAdvMedical#19]
**Arma 3 Version:** `x.xx` (stable, last version)
**CBA Version:** `v3.9.1.181229` (stable, last version on Steam)
**ACE3 Version:** `3.12.5` (stable, last version on Steam)
**KAM Version:** `(last version on Steam)

**Mods:**
```
- CBA_A3
- ace
- KAM
```

**Description:**
- I can intubate without overstretching.

**Steps to reproduce:**
- Have the tube in the inventory.
- One person must be unconscious
- try to intubate without doing anything before.

**Where did the issue occur?**
- Self-Hosted Multiplayer (haven't tried with Dedicated)

**What should have happened**
I think that the overstretching is meant to be a requierement before intubating the pacient. You should not be able to see the intubation option before overstretching the head or maybe cause more damage to the pacient if you did intubate without overstretching. If I am misunderstading something, let me know.

**Comment by Katalam** [comment]
No not really. The overstretching is the action a normal rifleman can do to save a life when no medic is near. I know that it would be more realistic to overstretch before intubating but it is still a game.

**Comment by corp-0** [comment]
So in this context, what does overstretching do?

**Comment by Katalam** [comment]
When you and your buddy clearing a building, your team made get shot and need help. You can save him until the platoon medic arrives

**Comment by corp-0** [comment]
Yeah, ok but I mean in the code.  What does it do? How does it help?

**Comment by Katalam** [comment]
It will stop the death timer to count down and stop the alternative timer to count the spO2 down. But will not restart it

**Comment by corp-0** [comment]
Maybe what we need is some documentation to know what does every new option do. How does the ace_airway death timer work? Is it running in parallel to the normal ace death timer? Is it replacing it?

I can help you doing the documentation if you wish, but I need to understand everything first

**Comment by Katalam** [comment]
I will work on a documentation. The death timer will be parallel

**Comment by corp-0** [comment]
Alright then I'll close the issue. Thank you for your time!
