### ISSUE TITLE
Script error while driving on a quad bike

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#2]
```
16:59:19 Error in expression <it", "_time", "_timeWithoutAir"];

if !(local _unit) then {
["deathTimer", ["_un>
16:59:19   Error position: <local _unit) then {
["deathTimer", ["_un>
16:59:19   Error local: Type String, expected Object,Group
16:59:19 File kat_aceAirway\functions\fn_handleTimer.sqf [kat_aceAirway_fnc_handleTimer], line 19
```

**Description:**
- Script error when being shot while sitting on a quad bike.

**Steps to reproduce:**
- idk, maybe be a BLUFOR player take a Quad and drive into an OPFOR roadblock.

**Where did the issue occur?**
- Dedicated

**RPT log file:**
https://paste.dth.rocks/?589492596086bb1d#6k8NTlLhjCSQuGmqWVQlTzmXTz823zBok4GkmroBlEo=

**Comment by Katalam** [comment]
308d383 - This will change it. Ready to test it. There was a problem with the parameter if i the unit wasnt local. Fixed.
