### ISSUE TITLE
Feture request: Diagnosing patients for wounds

### ISSUE THREAD

**Issue by Koda501** [Katalam/kat_aceAdvMedical#20]
- You must first diagnose someone to see what wounds and where they have them. 

- after diagnosing someone their medical menu starts to reveal injuries, IVs, Tourniquets, etc 

This is to simulate a "visual" quick check from head to toe of the patient that would reveal stuff such as; 1x velocity wound to the right arm, 1x tourniquet is currently applied to the right arm, the patient is not breathing, etc. 

The reason for this change is that it would cause everyone that is wounded or treating someone to take the time to look themselves/someone over thoroughly rather than approaching every situation the same by throwing tourniquets at the problem and calling it a day.

**Comment by 0xlord** [comment]
Looking into the medical menu and/or interaction section is already like a first look in which even a normal person could distinguish a bullet wound from a scratch from a cut and so on. 
What could make sense would be a reveal of only advanced injuries like thorax injuries and other.

**Comment by Katalam** [comment]
There is something that is called cutofClothes. Basically it will throw your stuff on the ground and delete your uniform. The reason of it, is the body check for a bee sting when you are alergical, maybe that is something in this direction

**Comment by Katalam** [comment]
I will think about it later again, but at the moment there is no need for a diagnostic check. If I'm better with GUIs maybe i can add something like a stethoscope for checking the lungs but not at the moment. But thanks for thinking about it. If you wanna have this exspecially for your unit you could join my discord and maybe I can get make it for you.

But for the moment. Closed.
