### ISSUE TITLE
Bugs beim Atemweg freimachen

### ISSUE THREAD

**Issue by FetterHobbit** [Katalam/kat_aceAdvMedical#22]
Die Sounds vom Acuvac spinnen rum und werden 10x gleichzeitig abgespielt.

Nach dem ich jemanden die Atemwege freigemacht hatte ist er aufgewacht trotz Nuller Puls. Er ist dann nach 2m Laufweg wieder zusammengebrochen.

Sound vom Monitor ist recht laut, gerade beim flatline sound.

Der Monitor ist ein bissi Overpowered weil er alle Werte einfach anzeigt.

**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- Add a detailed description of the error. This makes it easier for me to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Add the list of modules you have placed on the map. Use 'None' if the error occurs without any modules.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Katalam** [comment]
Das er aufwacht dürfte nicht passieren. Ich mache da sehr wenig am revive Timer also eigentlich nichts. Joa der Monitor ist OP, soll er auch. Ist eine Sache für einen Platoon Medic nicht für den Combat Life Saver. Joa Sound wurde leiser gestellt im letzten Update.
