### ISSUE TITLE
Bug: same class names for painkillers mag and weapon

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#23]
I think there is a problem with using the exact same classnames for the painkillers weapon and magazine. When I run ```this addItemToUniform "KAT_Painkillers";``` you get an invisible item in your inventory. When you run ```cursorTarget addMagazineCargoGlobal ["KAT_painkillers", 1]``` on a container you get the correct items, but then when you take one into your inventory it's still the same. When you now export your loadout (after you have taken the correct item into your inventory - item has a pic and ACE actions are available) you get the entry ```this addItemToUniform "KAT_Painkillers";```. I assume this is because it can't decide what kind of item it is due to the same classname being used for both the magazine and the weapon. And before you ask, yes you add real magazines using ```addItemToUniform``` as well, e.g., ```this addItemToUniform "16Rnd_9x21_Mag";``` and it works correctly.

Please rename the weapon classname of painkillers. Acutally, now that I think of I am not sure why you would net that at all.

**Comment by Katalam** [comment]
Maybe you can use this: `player addMagazine "KAT_Painkillers"`
If this don't work for you, I will look a bit more detailed, but for me it worked.

**Comment by Katalam** [comment]
With adc688b3076af6a3c4aac03f14d7856e8dc4e633 it should be fixed. New Classname will be `KAT_Painkiller`
