### ISSUE TITLE
Negative SpO2 

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#24]
Is the SpO2 supposed to drop into the negative range? Yesterday we had this case, no script error nothing. The patient was in a helicopter explosion and was dragged away. First responders worked for about 5 minutes before the Medic came  and diagnosed negative SpO2.

![20190214201953_1](https://user-images.githubusercontent.com/23381725/52857538-c039a680-3127-11e9-9f9c-7ec678c2ff50.jpg)
![20190214202008_1](https://user-images.githubusercontent.com/23381725/52857540-c039a680-3127-11e9-91f6-8718c2017fff.jpg)

**Comment by Katalam** [comment]
Solved in f2ed5d5851f25457c1403fb576fc72e52276c272
