### ISSUE TITLE
AED X Heart Rate

### ISSUE THREAD

**Issue by SBaconator** [Katalam/kat_aceAdvMedical#26]
**Arma 3 Version:** `1.88` (stable)
**CBA Version:** `3.9.1.181229` (stable)
**ACE3 Version:** `3.12.5` (stable)

**Mods:**
```
- CBA_A3
- ace
- ace advanced CPR
- ace advanced splints
- RHS
- CUP Core
- CUP Terrains Core
- Aniyza 
- Ace Compat RHS
- JSRS
- Shacktack
- Blastcore standalone
```

**Description:**
- AED X will read and beep as if the patient has a heart rate. But when checking pulse Heart rate is absent. Patient will be fully healed and won't get up and upon checking their pulse manually the heart rate has stopped. AED X will resume monitoring the patients vitals when the heart has restarted. 

**Steps to reproduce:**
-Injure patient with significant force, bomb, grenade, or multiple bullet wounds. 
-Attach AED X, to monitor vitals
-Check monitor vitals against check pulse to see difference 

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Placed Modules:**
-Zeus Module x2

**RPT log file:**
- No RPT file

**Comment by Katalam** [comment]
Closed. Medical rewrite will change the problem. No update until medical rewrite is live.
