### ISSUE TITLE
Tourniquet display in medical menu broken with current ACE3 update

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#29]
When having your 0.9.9.5 version enabled with newest ACE3, the functions for the tourniquets does not work, instead it only looks like this:
![20190317224110_1](https://user-images.githubusercontent.com/23381725/54498302-e3619c80-4905-11e9-9628-eabe88a96183.jpg)

**Comment by Katalam** [comment]
9cc2f0b3e9034d979d935a6e5adf856a012d15ce I think I've fixed it. Problem is here: https://github.com/acemod/ACE3/commit/88eb74348536a67cc7023cd8fc6ea5d5ad9ad23a

but I already got this:
https://github.com/Katalam/kat_aceAdvMedical/blob/9cc2f0b3e9034d979d935a6e5adf856a012d15ce/addons/kat_aceairway/functions/fn_displayPatientInformation.sqf#L168-L169

**Comment by Katalam** [comment]
Fixed it
