### ISSUE TITLE
"intubiert mit any" 

### ISSUE THREAD

**Issue by Schwaggot** [Katalam/kat_aceAdvMedical#4]
![20181107213129_1](https://user-images.githubusercontent.com/23381725/48159119-a987e600-e2d4-11e8-9b6d-c41952e2ce76.jpg)
Nach Intubation mit Laryxn Tube kam im Chat die Meldung "intubiert mit any"

**Comment by Katalam** [comment]
This should be fixed in commit 78d8c2f just check it again with the actual release. If the message will appear continuously just commend a second pls.

**Comment by Katalam** [comment]
d3232e8
This will fix it, there was some issues with a private variable which is not available outside the switch case. Sometimes its not perfect to use private variables.
Fixed and closed
